version: '3'
services:
  asbapp:
    build: .
    command: npm run dev
    volumes:
      - .:/app/src
      - /app/src/node_modules
    ports:
      - "80:3000"
    depends_on:
      - postgres
    environment: 
        DATABASE_URL: postgres://postgres:gunsmoke97@postgres:5432/asb
  
  postgres:
    image: postgres:12
    ports: 
        - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gunsmoke97
      POSTGRES_DB: asb